### PR TITLE
Project Asset

### LINKED ISSUE #6: Review and possibly simplify the code
Josh worked on this character directly, I just briefly looked at the code, so it could use a second pair of eyes. Go through the character's code and look for places where it can be simplified or refined.

Josh suggested to replace rotation logic with quaternions, which would shorten the code and prevent issues like gimbal lock or the need to unwind in some case. He went with rotation in degrees as this will end up in a tutorial, because quaternions are harder to understand compared to angles.

But as quaternions solve some problems that can be tricky when you use angles and can easily produce smooth, graceful rotations, we should consider using them.

## Tasks

- [ ] Review the code and simplify if possible
- [ ] Document the main scripts with a docstring at the top
- [ ] Figure out if we should use quaternions (you can create a new task for that)

### PR DESCRIPTION
**Pull request by Razoric480**
First pass - updated readme file with some getting started information. Added header documentation to classes, removed the Zip/Hang states into an optional Extensions folder.

Comment: Needing to Modify the Move state to add the Zip and Hang states is a downside. If we collect new extension states from contributors, we get the equivalent of merge conflicts - though it's not as bad if we can just use signals, then it's just a series of signal connections instead of actual hard logic.

Also the writing is likely going to need proof reading. I'm competent at formal writing, but probably not the clearest.

Close #6

### CODE REVIEW

**Comment by NathanLovato** [comment]
I made some more changes, in particular as the camera depends on the player and vice versa, they shouldn't be separate nodes in the tree imo, so I made them work in the same scene. Then the camera stays saved as a separate scene for version control. It should do for now. We can always improve it in the future.

**Comment by NathanLovato** [comment]
Thanks for your work 🙂

**Comment by Razoric480** [comment]
♥ I'll be moving on to the assignments for the platform course, then.

**Comment by Razoric480** [comment]
Tweaked the comments, and made an icon that wasn't just the godot icon, for kicks. Otherwise, your changes look quite nice - I'm out of stuff to add to it!

**Pull request merged**
